# Header
menu:
  Home: /
  Archives: /archives
  Github: https://github.com/zhangjindong/zhangjindong.github.io
# rss: /atom.xml

# Content
excerpt_link: read more

# Favicon
# favicon: /favicon.ico

# Settings toggle
settings: true

# Code CSS toggle
highlight: true

# Word count (needs hexo-wordcount)
word_count: true

# Google Analytics
google_analytics:
  enable: false
  acct: "UA-000000000-0"

# IntenseDebate ID
intensedebate:
  enable: true
  acct: "6209ec1f60e469c615e515a9b4426504"
